### ISSUE TITLE
Lower hardware configuration virtual machines start all the environments that report errors .

### ISSUE THREAD

**Issue by shiyi2014** [jetlinks/jetlinks-docs#1]
The cause is low memory.
It is recommended to add basic hardware requirements to the development documentation

**Comment by friedrichfei** [comment]
设备消息协议解析sdk的消息组成，第一点：是否异步拼写aysnc的问题。

**Comment by zhou-hao** [comment]
> The cause is low memory.
> It is recommended to add basic hardware requirements to the development documentation

可以使用内嵌方式启动 http://doc.jetlinks.cn/install-deployment/not-docker-start.html#%E4%BD%BF%E7%94%A8%E5%86%85%E5%B5%8C%E6%89%80%E9%9C%80%E7%8E%AF%E5%A2%83%E7%9A%84%E6%96%B9%E5%BC%8F%E5%90%AF%E5%8A%A8jetlinks%E6%9C%8D%E5%8A%A1
