### ISSUE TITLE
咱们的操作文档里面没有一份完整的平台对接某种物理传感器的操作手册吗？

### ISSUE THREAD

**Issue by wanggang20201222** [jetlinks/jetlinks-docs#11]

**Comment by wanggang20201222** [comment]
咱们的操作文档里面没有一份完整的平台对接某种物理传感器的操作手册吗？

**Comment by wangzheng0723** [comment]
http://doc.jetlinks.cn/advancement-guide/mqtt-connection.html

**Comment by AsuKa1989** [comment]
http://doc.jetlinks.cn/basics-guide/DemoDevice.html 如需购买请加QQ群 2021514
