### ISSUE TITLE
EMQ 官网地址错误

### ISSUE THREAD

**Issue by CrazyWisdom** [jetlinks/jetlinks-docs#37]
http://doc.jetlinks.cn/advancement-guide/third-mqtt.html#%E5%AE%89%E8%A3%85%E5%B9%B6%E5%90%AF%E5%8A%A8emq

页面里的 EMQ 官网地址是错的，正确地址应为 [https://www.emqx.com](https://www.emqx.com)（[emqtt.io](https://www.emqtt.io) 域名已不属于 EMQ 公司）。

请帮忙更新下，谢谢！

<img width="454" alt="image" src="https://user-images.githubusercontent.com/1215191/135216080-5e44013a-4f89-4bb3-b2bf-9676326c97f9.png">

**Comment by zhou-hao** [comment]
https://www.emqx.cn 也是吧

**Comment by CrazyWisdom** [comment]
> https://www.emqx.cn 也是吧

https://www.emqx.cn 是之前的中文官网，现在会自动跳转到 https://www.emqx.com/zh。
https://www.emqx.io 是之前的英文官网，现在改为了 EMQ X 项目的开发者社区站。

emqx.cn 跟 emqx.io 这两个不改也没问题。
