### ISSUE TITLE
文档图片无法打开

### ISSUE THREAD

**Issue by 1183245696** [jetlinks/jetlinks-docs#40]

**Comment by zhou-hao** [comment]
提供一下文档链接

**Comment by 1183245696** [comment]
http://doc.jetlinks.cn/






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月7日(星期二) 下午5:59
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jetlinks/jetlinks-docs] 文档图片无法打开 (Issue #40)





 
提供一下文档链接
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zhou-hao** [comment]
![image](https://user-images.githubusercontent.com/7791838/145008673-dc2cca43-fe12-4669-945a-4a8740665282.png)

可以打开的哟

**Comment by 1183245696** [comment]
这种的，原来就是这样吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月7日(星期二) 晚上6:04
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jetlinks/jetlinks-docs] 文档图片无法打开 (Issue #40)





 

 
可以打开的哟
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
