### ISSUE TITLE
文档中写ClickHouse-行式存储

### ISSUE THREAD

**Issue by dobean** [jetlinks/jetlinks-docs#43]
http://doc.jetlinks.cn/best-practices/start.html#clickhouse-%E8%A1%8C%E5%BC%8F%E5%AD%98%E5%82%A8

ClickHouse是列式存储

ClickHouse® is an open-source, high performance columnar OLAP database management system for real-time analytics using SQL.

**Comment by zhou-hao** [comment]
这里说的行式列式 指的是设备属性数据存储的方式。

行式： 一个设备一个属性值为一行数据

列式：一次数据上报为一行，一个属性值为一列。
