### ISSUE TITLE
文档缺失：使用docker安装所需环境(redis,elasticsearch,PostgreSQL). 

### ISSUE THREAD

**Issue by EnthuDai** [jetlinks/jetlinks-docs#7]
由  http://doc.jetlinks.cn/install-deployment/start-with-source.html#%E7%B3%BB%E7%BB%9F%E7%8E%AF%E5%A2%83
中 “使用docker安装所需环境” 链接http://doc.jetlinks.cn/install-deployment/ide-docker-start.html 指向的页面内容缺失

**Comment by dongfangpiaoyun** [comment]
我也发现了同样的情况
