### ISSUE TITLE
TCP透传接入时，设备网关新增界面中“类型”下拉框内容与实际内容不匹配

### ISSUE THREAD

**Issue by EnthuDai** [jetlinks/jetlinks-docs#9]
文档地址： http://doc.jetlinks.cn/best-practices/tcp-connection.html#%E5%88%9B%E5%BB%BAtcp%E6%9C%8D%E5%8A%A1%E7%BD%91%E7%BB%9C%E7%BB%84%E4%BB%B6 ，在1.7release版本中，设备网关类型只有“MQTT broker接入”、“MQTT直接接入”、"TCP透传接入"，未看到有文档中所示的“TCP服务设备网关”

**Comment by zhou-hao** [comment]
TCP透传接入 就是TCP服务设备网关
